title: Quick and dirty work
author:
  name: "Dmitrii Safronov"
  email: "zimniy@cyberbrain.pw"
description: Pet projects, crutches and bicycles.
##########################################################################

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

##########################################################################

remote_theme: "jekyll/minima@f1a2af4"

##########################################################################

minima:
  skin: auto
  date_format: "%Y %b %-d"
  show_excerpts: true
  social_links:
    - title: disafronov
      icon: github
      url: "https://github.com/disafronov"
    - title: zimniy
      icon: linkedin
      url: "https://www.linkedin.com/in/zimniy/"

disqus:
  shortname: cyberbrain-pw

google_analytics: G-VWE7QJCSVH

##########################################################################

defaults:
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false
