title: Quick and dirty work
author:
  name: "Dmitrii Safronov"
  email: "zimniy@cyberbrain.cc"
description: Pet projects, crutches and bicycles =)

##########################################################################

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

##########################################################################

remote_theme: "jekyll/minima@f1a2af4"

##########################################################################

minima:
  skin: auto
  date_format: "%Y %b %-d"
  show_excerpts: true
  social_links:
    - title: disafronov
      icon: github
      url: "https://github.com/disafronov"
    - title: zimniy
      icon: linkedin
      url: "https://www.linkedin.com/in/zimniy/"
  nav_pages:
    - about.md

disqus:
  shortname: quick-and-dirty-work

google_analytics: G-HYCH7BQJ57

##########################################################################

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false
